config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"
  get 'about', to: 'top#about'
  resources :top, only: [:index] do
    resource :likes, only: [:create, :destroy]
  end
  resources :fukyos do
    resources :comments
    resource :likes, only: [:create, :destroy]
  end
  resources :odais do
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :text, length: { maximum: 140 }
	belongs_to :fukyo
	belongs_to :user
end

app/models/fukyo.rb
class Fukyo < ApplicationRecord
	validates :detail, length: { maximum: 150 }
	validates :title, presence: true, length: { maximum: 140 }
	validates :URL, length: { maximum: 255 }
	belongs_to :odai
	belongs_to :user
	has_many :comments, :dependent => :delete_all
	has_many :likes, dependent: :destroy
	def like_user(user_id)
	  likes.find_by(user_id: user_id)
	end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :fukyo, counter_cache: :likes_count
  belongs_to :user
end

app/models/odai.rb
class Odai < ApplicationRecord
	has_many :fukyos, :dependent => :destroy
	belongs_to :user
	validates :user_id, presence: true
	validates :detail, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { maximum: 12 }
  validates :email, presence: true, length: { maximum: 255 }
  has_many :odais, :dependent => :destroy
  has_many :fukyos, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :fukyo
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]
  
   def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        username: auth.info.name
      )
      user.skip_confirmation!
      user.save
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    top_index_path
  end
  def after_sign_out_path_for(resource)
    top_index_path
  end

  private
    def sign_in_required
      redirect_to new_user_session_url unless user_signed_in?
    end
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
    end

end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :sign_in_required, only: [:create, :destroy]
  def create
  	@comment = Comment.create(text: comment_params[:text], fukyo_id: comment_params[:fukyo_id], user_id: current_user.id)
    redirect_to "/fukyos/#{@comment.fukyo.id}" 
  end

  def destroy
	comment = Comment.find(params[:id])
		if comment.user_id == current_user.id
			comment.destroy
      redirect_to "/fukyos/#{comment.fukyo.id}" 
		end
  end

  private
  def comment_params
  	params.permit(:text, :fukyo_id)
  end
end

app/controllers/fukyos_controller.rb
class FukyosController < ApplicationController
	before_action :sign_in_required, only: [:new, :create, :destroy]

	def new
	  @odai = Odai.find(params[:odai_id])
	  @fukyo = Fukyo.new
	  @fukyo.odai_id = @odai.id
	end

	def create
    @fukyo = Fukyo.create(fukyo_params)
    FukyoMailer.fukyo_notify(@fukyo).deliver_now 
    redirect_to root_url
	end

	def show
	  @fukyo = Fukyo.find(params[:id])
	  @comments = Comment.includes(:user).page(params[:page]).per(10).order("created_at DESC")
	end

	def destroy
		fukyo = Fukyo.find(params[:id])
		if fukyo.user_id == current_user.id
			fukyo.destroy
			redirect_to root_url
		end
	end

	private
	def fukyo_params
	  params.require(:fukyo).permit(:odai_id, :title, :URL, :detail).merge(user_id: current_user.id)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :sign_in_required, only: [:create, :destroy] 
  def create
    @fukyo= Fukyo.find(params[:fukyo_id])
    @like = @fukyo.likes.create(user_id: current_user.id)
    @likes =@fukyo.likes
    @fukyos = Fukyo.all
  end

  def destroy
    @fukyo = Fukyo.find(params[:fukyo_id])
    like = @fukyo.likes.find_by(user_id: current_user.id)
    like.destroy
    @likes = @fukyo.likes
    @fukyos = Fukyo.all
  end

end

app/controllers/odais_controller.rb
class OdaisController < ApplicationController
	before_action :sign_in_required, only: [:new, :create, :destroy]
	def index
		@odais = Odai.find(params[:id])
		@fukyos = @odais.fukyos
	end

	def new
	end

	def create
		@odai = Odai.create(odai_params)
	end

	def show
		@odai = Odai.find(params[:id])
		@fukyos = @odai.fukyos
	end

	def destroy
		odai = Odai.find(params[:id])
		if odai.user_id == current_user.id
			odai.destroy
			redirect_to root_url
		end
	end

	private
	def odai_params
	  params.require(:odai).permit(:detail).merge(user_id: current_user.id)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
	@odais = Odai.includes(:user).page(params[:page]).per(10).order("created_at DESC")
	@fukyos = Fukyo.includes(:user).page(params[:page]).per(10).order("created_at DESC")
  @odai = Odai.new
  #@odaiの中身がnilになってしまうためここでnewする
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_in_required, only: [:edit, :update]
  def show
  	@user = User.find(params[:id])
    @username = @user.username
  	@odais = @user.odais.page(params[:page]).per(10).order("created_at DESC")
  	@fukyos = @user.fukyos.page(params[:page]).per(10).order("created_at DESC")
    @likefukyos = @user.likes
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  	@user.update_attributes(update_params)
  end

  private
  def update_params
  	params.require(:user).permit(:username, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #devisesフォルダ以外のviewでもdevise関係のメソッドが使えるようになる
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def user_avatar(user)
    if user.avatar.attached?
      image_tag user.avatar.variant(resize: "100x80"), :alt => "UserIcon"
    else
      image_tag "/Noimage.png", :size => '80x80', :alt => "NoimageUserIcon"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fukyos_helper.rb
module FukyosHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/odais_helper.rb
module OdaisHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/comments/create.html.erb
<p>コメントを投稿しました。</p>
<%= link_to "コメント一覧に戻る", "/fukyos/#{@comment.fukyo.id}" %>

app/views/comments/destroy.html.erb
<p>コメントを削除しました。</p>

<%= link_to "トップに戻る", "/" %>

app/views/fukyos/index.html.erb
<table>
  <tr>
    <th>お題</th>
    <th>布教タイトル</th>
    <th>布教詳細</th>
    <th>布教URL</th>
  </tr>
<% @fukyos.each do |fukyo| %>
  <tr>
    <td><%= fukyo.odai.detail %></td>
    <td><%= fukyo.title  %></td>
    <td><%= fukyo.detail %></td>
    <td><%= fukyo.URL %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Back' , top_index_path %>

app/views/fukyos/new.html.erb
<span class= "odai">お題：</span><span class= "detail" ><%= @odai.detail %></span>
<div class="fukyoform">
  <%= form_for(@fukyo) do |f| %>
    <%= f.text_area :title, placeholder: "タイトルを入力(必須・140文字以内)", cols:"30", rows:"3", autofocus:"true", required: true %>
    <%= f.text_area :detail, placeholder: "詳細を入力(自由記入・500字以内)", cols:"30", rows:"8", autofocus:"true" %>
    <%= f.text_area :URL, placeholder: "URLを入力(自由記入)", cols:"30", rows:"3", autofocus:"true" %>
    <%= f.hidden_field :odai_id %>
    <%= f.submit "布教する", :class =>"btn btn-info" %>
<% end %>
</div>

app/views/fukyos/show.html.erb
 <% provide(:description,"布教タイトル:" + @fukyo.title.to_s.truncate(30) + "布教詳細:" + @fukyo.detail.truncate(30))%>
 <% provide(:site_url,url_for( :only_path => false)) %>
  <div class= "fukyoshow">
    <span class="odaidetail">お題:<%= @fukyo.odai.detail %></br></span>
    布教タイトル：<%= @fukyo.title %></br>
    布教詳細：<%= @fukyo.detail %></br>
    布教URL:<td><%= link_to @fukyo.URL, @fukyo.URL, :target => "_blank" %></td></br>
    <a href="http://twitter.com/share?url=<%= url_for( :only_path => false) %>&amp;text=お題:「<%= @fukyo.odai.detail %>」- 布教:「<%= @fukyo.title.truncate(60) %>」布教の詳細は→&amp;related=kiryuanzu&amp;hashtags=fukyobako" id="tweet" class="btn btn-info withripple btn-lg" target="_blank" name="tweet">布教をTwitterで共有する</a>
  </div>
	  <% if current_user %>
        <div class="like">
        ナイス布教！<%= render partial: 'likes/like', locals: {fukyo: @fukyo} %>
        </div>
        <div class="commentsform" >
        <%= form_tag("/fukyos/#{@fukyo.id}/comments", method: :post) do %>
        <textarea cols="100" name="text" placeholder="コメントする(140字以内）" rows="3"></textarea>
        <input type="submit" value="SEND" class ="btn btn-info" >
        <% end %>
    <% else %>
    <p><span class="comment-login"><%= link_to "新規登録", new_registration_path(resource_name) %>or<%= link_to "ログイン", new_session_path(resource_name) %>してコメントする</span></p>
      </div>
      <% end %>
        <span class= "fukyonusi"> 布教したユーザーは布教主として名前を隠してコメントができます。</span>
        <h4><コメント一覧></h4>
        <div class= "comments">
        <% if @fukyo.comments %>
          <div class="table-responsive">
          <table class="table table-condensed" >
            <% @fukyo.comments.each do |comment| %>
             <tr　class="something"　>
                <th>ユーザー</th>
                <th>コメント</th>
                <th>削除</th>
             </tr>         
          <tr>
             <% if comment.user == @fukyo.user %>
               <td  class= "col-md-3"><%= image_tag '/Noimage.png', :size => '100x100' %>
    　         <p>布教主</p></td>
             <% else %>
               <td  class= "col-md-3">
                  <%= user_avatar(comment.user) %>
                  <p><%= comment.user.username %></p>
             <% end %>
            <td><%= comment.text %></td>
            <td>
              <% if user_signed_in? && current_user.id == comment.user_id %>
            <%= link_to '削除', "/fukyos/#{@fukyo.id}/comments/#{comment.id}", method: :delete %>
            </td>
            <td>
              <a href="http://twitter.com/share?url=<%= url_for( :only_path => false) %>&amp;text=<%= comment.text %>/お題:「<%= @fukyo.odai.detail %>」 - 布教タイトル:「<%= @fukyo.title %>」布教詳細等は→&amp;related=kiryuanzu&amp;hashtags=fukyobako" id="tweet" class="btn btn-info withripple btn-small" target="_blank" name="tweet">Twitterで布教とコメントを共有する</a>
            </td>
            <% end %>
            </tr>
            <% end %>
        <% end %>
        <%= paginate(@comments) %>

        </table>
        </div>
      </div>

    </div>
</div>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if fukyo.like_user(current_user.id) %>
    <%= button_to fukyo_likes_path(fukyo), method: :delete, id: "like-button", remote: true do %>
      <%= fa_icon 'heart' %>
      <span>
        <%= fukyo.likes_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to fukyo_likes_path(fukyo), id: "like-button", remote: true do %>
      <%= fa_icon 'heart-o' %>
      <span>
        <%= fukyo.likes_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <%= fa_icon 'heart' %>
    <span>
      <%= fukyo.likes_count %>
    </span>
<% end %>

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'likes/like', locals: { fukyo: @fukyo, fukyos: @fukyos, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'likes/like', locals: { fukyo: @fukyo, fukyos: @fukyos, likes: @likes }) %>");

app/views/odais/_fukyo.html.erb
<div class ="fukyo" > 
<table class="table table-striped table-responsive">
  <tr class="something">
    <th>お題</th>
    <th>布教タイトル</th>
    <th>布教詳細</th>
    <th>布教URL</th>
  </tr>
  <tr class="something">
    <td class= "col-md-3" ><%= fukyo.odai.detail %></td>
    <td class= "col-md-3"><%= fukyo.title  %></td>
    <td td class= "col-md-3" ><%= fukyo.detail %></td>
    <td><%= link_to fukyo.URL, fukyo.URL, :target => "_blank" %></td>
    <td><%= link_to "コメントする", fukyo_path(fukyo.id), method: :get %>
    <% if user_signed_in? && current_user.id == fukyo.user_id %>
    <td><%= link_to '削除', "/fukyos/#{fukyo.id}", method: :delete %>
    </td>
      <% end %>
  </tr>
</table>
</div>

app/views/odais/_new.html.erb
<div class="odaiform">
  <%= form_for(@odai) do |f| %>
    <h3>
      布教して欲しいお題を投稿しましょう(140字以内)
    </h3>
    <%= f.text_area :detail, cols:"80", placeholder:"（例：◯◯なキャラが出る作品、ストーリーが◯◯な作品など自分が見たい/読みたいと思っているイメージを書いてみましょう）", rows:"3", required: true %>
    <%= f.submit "お題を投稿", :class =>"btn btn-primary" %>
  <% end %>
</div>

app/views/odais/create.html.erb
<h3>お題を投稿しました!</h3>
<a href="http://twitter.com/share?url=https://fukyobako.herokuapp.com/odais/<%= @odai.id %>&amp;text=<%= @odai.user.username %>さんのお題:「<%= @odai.detail.truncate(90) %>」にレッツ布教！&amp;related=kiryuanzu&amp;hashtags=fukyobako" id="tweet" class="btn btn-info withripple btn-lg" target="_blank" name="tweet">twitterでお題を共有する</a>

<%= link_to "ホームに戻る", root_path %>

app/views/odais/index.html.erb
<table>
  <tr>
    <th>お題を出した人の名前</th>
    <th>お題</th>
    <th>布教ボタン</th>
  </tr>
<% @odais.each do |odai| %>
  <tr>
    <td><%= odai.user.username %>
    <td><%= odai.detail :class => :"h3" %></td>
    <td><%= form_tag(new_fukyo_path, method: :get) do %>
      <%= hidden_field_tag(:odai_id, odai.id) %>
      <%= submit_tag("布教する") %>
    </td>
    <% if user_signed_in? && current_user.id == odai.user_id %>
    <td><%= link_to '削除', "/fukyos/#{fukyo.id}", method: :delete %>
    </td>
      <% end %>
  </tr>
<% end %>
</table>

app/views/odais/show.html.erb
 <% provide(:description,"お題:"+ @odai.detail.to_s) %>
 <% provide(:site_url,url_for( :only_path => false)) %>
<span class= "odai">お題：</span>
  <span class= "detail" >
	<%= @odai.detail %>
  </span>
  <p><a href="http://twitter.com/share?url=https://fukyobako.herokuapp.com/odais/<%= @odai.id %>&amp;text=<%= @odai.user.username %>さんのお題:「<%= @odai.detail.truncate(90) %>」にレッツ布教！&amp;related=kiryuanzu&amp;hashtags=fukyobako" id="tweet" class="btn btn-info withripple btn-lg" target="_blank" name="tweet">twitterでお題を共有する</a></p>
 <%= form_tag(new_fukyo_path, method: :get ) do %>
      <%= hidden_field_tag(:odai_id, @odai.id) %>
      <%= submit_tag("布教する", :class =>"btn btn-default btn-lg") %>
      <% end %>

<%= render partial: "odais/fukyo", collection: @fukyos %>

app/views/users/_contents.html.erb
<div id="top-index">
  <ul class="tab">
    <li><a href="#tab1" class="selected">お題一覧/布教する</a></li>
    <li><a href="#tab2">布教一覧</a></li>
    <li><a href="#tab3">ナイス布教欄</a></li>
  </ul>
  <ul class="panel">
    <li id="tab1">
    <table class="table">
  <tr class="something" >
    <th>お題</th>
    <th>布教ボタン</th>
  </tr>
<% @odais.each do |odai| %>
  <tr>
     <td class="title"><%= odai.detail %></td>
    <td><%= form_tag(new_fukyo_path, method: :get) do %>
      <%= hidden_field_tag(:odai_id, odai.id) %>
      <%= submit_tag("布教する", :class =>"btn btn-info") %>
      <% end %>
    </td>
    <td>
    <%= link_to "このお題の布教一覧", odai_path(odai.id), method: :get, :class =>"btn btn-success" %>
    </td>
  </tr>
<% end %>
<%= paginate(@odais) %>
<% if user_signed_in? && current_user.id == @user.id  %>
</table>
    </li>
    <li id="tab2">
  <table class="table">
  <tr>
    <th>お題</th>
    <th>布教タイトル</th>
    <th>布教詳細</th>
    <th>布教URL</th>
  </tr>
<% @fukyos.each do |fukyo| %>
  <tr>
   <td><%= link_to fukyo.odai.detail, "odais/#{fukyo.odai.id}" %></td>
    <td><%= link_to fukyo.title, "/fukyos/#{fukyo.id}" %></td>
    <td><%= fukyo.detail %></td>
    <td><%= link_to fukyo.URL, fukyo.URL, :target => "_blank" %></td>
     <% if user_signed_in? && current_user.id == fukyo.user_id %>
    <td><%= link_to '削除', "/fukyos/#{fukyo.id}", :class =>"btn btn-danger", method: :delete %>
    <% end %>
  </tr>
<% end %>
<%= paginate(@fukyos) %>
<% end %>
</table>
 <li id="tab3">
    <table class="table">
    <tr>
    <th>お題</th>
    <th>布教タイトル</th>
    <th>布教詳細</th>
    <th>布教URL</th>
  </tr>
  <% @likefukyos.each do |like| %>
  <tr>
  <td><%= like.fukyo.title %></td>
    <td><%= like.fukyo.detail %></td>
    <td><%= link_to like.fukyo.URL %></td>
  </tr>
  <% end %>
</table>
  </li>
  </ul>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user, local: true do |f| %>
  <h2>名前を変更</h2>
    <div class="form-group">
      <%= f.text_field :username, placeholder: "name(12文字以内)" %>
    </div>
  <h2>プロフィール画像を変更</h2>
    <%= f.file_field :avatar %>
    <%= f.submit "送信", class: "btn btn-primary withripple edit-submit-button" %>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "すでにアカウントを持っている", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れましたか?", new_password_path(resource_name) %><br />
<% end -%>

app/views/users/show.html.erb
<html>
  <head>
    <%= render 'top/script' %>
  </head>
  <body>
    <main>
      <% provide(:description,@user.username.to_s + "さんのページ") %>
      <% provide(:site_url,url_for( :only_path => false)) %>
      <span class=username>
        <span class= "name" ><%= @username %></span>
        <% if @user.avatar.attached?%>
          <span class="miniimage">
          <%= image_tag @user.avatar.variant(resize: "32x32")%>
          </span>
        <% end %>
        <span class="user" >さんのお題と布教一覧</span>
      </span>
    <% if user_signed_in? && current_user.id == @user.id  %>
      <div class="name-edit"><%= link_to '名前とアイコンを変更', edit_user_path(current_user), {class: 'btn btn-primary withripple' } %></div>
    <a href="http://twitter.com/share?url=<%= url_for( :only_path => false) %>&amp;text=<%= @user.username %>さんのお題一覧です。レッツ布教！&amp;related=kiryuanzu&amp;hashtags=fukyobako" id="tweet" class="btn btn-info withripple btn-lg" target="_blank" name="tweet">twitterでお題一覧を共有する</a>
    <% end %>
    <%= render 'users/contents' %>
    </main>
  </body>

app/views/users/update.html.erb
<h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>