config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"
  get 'about', to: 'top#about'
  resources :top, only: [:index] do
    resource :likes, only: [:create, :destroy]
  end
  resources :fukyos do
    resources :comments
    resource :likes, only: [:create, :destroy]
  end
  resources :odais do
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :text, length: { maximum: 140 }
	belongs_to :fukyo
	belongs_to :user
end

app/models/fukyo.rb
class Fukyo < ApplicationRecord
	validates :detail, length: { maximum: 150 }
	validates :title, presence: true, length: { maximum: 140 }
	validates :URL, length: { maximum: 255 }
	belongs_to :odai
	belongs_to :user
	has_many :comments, :dependent => :delete_all
	has_many :likes, dependent: :destroy
	def like_user(user_id)
	  likes.find_by(user_id: user_id)
	end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :fukyo, counter_cache: :likes_count
  belongs_to :user
end

app/models/odai.rb
class Odai < ApplicationRecord
	has_many :fukyos, :dependent => :destroy
	belongs_to :user
	validates :user_id, presence: true
	validates :detail, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { maximum: 12 }
  validates :email, presence: true, length: { maximum: 255 }
  has_many :odais, :dependent => :destroy
  has_many :fukyos, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :fukyo
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]
  
   def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        username: auth.info.name
      )
      user.skip_confirmation!
      user.save
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :sign_in_required, only: [:create, :destroy]
  def create
  	@comment = Comment.create(text: comment_params[:text], fukyo_id: comment_params[:fukyo_id], user_id: current_user.id)
    redirect_to "/fukyos/#{@comment.fukyo.id}" 
  end

  def destroy
	comment = Comment.find(params[:id])
		if comment.user_id == current_user.id
			comment.destroy
      redirect_to "/fukyos/#{comment.fukyo.id}" 
		end
  end

  private
  def comment_params
  	params.permit(:text, :fukyo_id)
  end
end

app/controllers/fukyos_controller.rb
class FukyosController < ApplicationController
	before_action :sign_in_required, only: [:new, :create, :destroy]

	def new
	  @odai = Odai.find(params[:odai_id])
	  @fukyo = Fukyo.new
	  @fukyo.odai_id = @odai.id
	end

	def create
    @fukyo = Fukyo.create(fukyo_params)
    FukyoMailer.fukyo_notify(@fukyo).deliver_now 
    redirect_to root_url
	end

	def show
	  @fukyo = Fukyo.find(params[:id])
	  @comments = Comment.includes(:user).page(params[:page]).per(10).order("created_at DESC")
	end

	def destroy
		fukyo = Fukyo.find(params[:id])
		if fukyo.user_id == current_user.id
			fukyo.destroy
			redirect_to root_url
		end
	end

	private
	def fukyo_params
	  params.require(:fukyo).permit(:odai_id, :title, :URL, :detail).merge(user_id: current_user.id)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :sign_in_required, only: [:create, :destroy] 
  def create
    @fukyo= Fukyo.find(params[:fukyo_id])
    @like = @fukyo.likes.create(user_id: current_user.id)
    @likes =@fukyo.likes
    @fukyos = Fukyo.all
  end

  def destroy
    @fukyo = Fukyo.find(params[:fukyo_id])
    like = @fukyo.likes.find_by(user_id: current_user.id)
    like.destroy
    @likes = @fukyo.likes
    @fukyos = Fukyo.all
  end

end

app/controllers/odais_controller.rb
class OdaisController < ApplicationController
	before_action :sign_in_required, only: [:new, :create, :destroy]
	def index
		@odais = Odai.find(params[:id])
		@fukyos = @odais.fukyos
	end

	def new
	end

	def create
		@odai = Odai.create(odai_params)
	end

	def show
		@odai = Odai.find(params[:id])
		@fukyos = @odai.fukyos
	end

	def destroy
		odai = Odai.find(params[:id])
		if odai.user_id == current_user.id
			odai.destroy
			redirect_to root_url
		end
	end

	private
	def odai_params
	  params.require(:odai).permit(:detail).merge(user_id: current_user.id)
	end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
	@odais = Odai.includes(:user).page(params[:page]).per(10).order("created_at DESC")
	@fukyos = Fukyo.includes(:user).page(params[:page]).per(10).order("created_at DESC")
  @odai = Odai.new
  #@odaiの中身がnilになってしまうためここでnewする
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_in_required, only: [:edit, :update]
  def show
  	@user = User.find(params[:id])
    @username = @user.username
  	@odais = @user.odais.page(params[:page]).per(10).order("created_at DESC")
  	@fukyos = @user.fukyos.page(params[:page]).per(10).order("created_at DESC")
    @likefukyos = @user.likes
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  	@user.update_attributes(update_params)
  end

  private
  def update_params
  	params.require(:user).permit(:username, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #devisesフォルダ以外のviewでもdevise関係のメソッドが使えるようになる
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def user_avatar(user)
    if user.avatar.attached?
      image_tag user.avatar.variant(resize: "100x80"), :alt => "UserIcon"
    else
      image_tag "/Noimage.png", :size => '80x80', :alt => "NoimageUserIcon"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fukyos_helper.rb
module FukyosHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/odais_helper.rb
module OdaisHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Fukyobako</title>
    <title><%= yield(:title) %> 布教箱</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="description" content="<%= yield(:description).presence || '布教してほしいお題を投稿する&匿名でお題に対する布教ができるWebサービス'%>">
    <meta name="keywords" content="布教,お題,投稿,布教箱,Twitter">

    <meta property="og:title" content="<%= yield(:title) %> 布教箱">
    <meta property="og:site_name" content="布教箱">
    <meta property="og:description" content="<%= yield(:description).presence || 
    '布教してほしいお題を投稿する&匿名でお題に対する布教ができるWebサービス'%>"/>
    <meta property="og:url" content="<%= yield(:site_url).presence || 'https://fukyobako.herokuapp.com'%>" />
    <meta property="og:image" content='https://fukyobako.herokuapp.com/assets/letsfukyo-5c6a98d77a551069964fbd86a8e8e4c5f45729bf9f50d8de6a0672b2a7ab94f1.png'/>
    <meta property="og:type" content="summary" />

    <meta name="twitter:card" content="summary" />

    <meta name="twitter:title" content="<%= yield(:title) %> | 布教箱">
    <meta name="twitter:description" content="<%= yield(:description).presence || '布教してほしいお題を投稿する&匿名でお題に対する布教ができるWebサービス'%>">
    <meta name="twitter:domain" content="Fukyobako.com">
    <meta name="twitter:image:src" content='https://fukyobako.herokuapp.com/assets/letsfukyo-5c6a98d77a551069964fbd86a8e8e4c5f45729bf9f50d8de6a0672b2a7ab94f1.png'%>"/>
    <!-- Place `favicon.ico` in the root directory. -->
    <link href="/apple-touch-icon.png" rel="apple-touch-icon">
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
       <nav>
        <%= link_to image_tag('/logo.png', { :class => "Fukyo-logo"} ), root_path %>
       
        <div class="profile" >
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                 <li>
                 <%= link_to '自分のプロフィール', user_path(current_user) %></li>
                 <li><%= link_to '設定', edit_user_registration_path %> </li>
                 <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                 <li><%= link_to '布教箱とは', about_path %></li>
            <% else %>
                <li><%= link_to 'サインアップ', new_user_registration_path %></li>
                <li><%= link_to 'ログイン', new_user_session_path %></li>
                <li><%= link_to'布教箱とは', about_path %></li>
              </ul>
                
            <% end %>
         </div>
        </nav>
     </div>
     </header>
     
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>